import { test, expect } from '@playwright/test';
import path from 'node:path';
const password='Sekolah123!';
async function login(page,role,identity,nisn){await page.goto('/login/'+role);await page.getByLabel(role==='admin'?'ID Admin':role==='teacher'?'ID atau nama lengkap guru':'Email murid',{exact:true}).fill(identity);if(nisn)await page.getByLabel('NISN',{exact:true}).fill(nisn);await page.getByLabel('Password / PIN pribadi',{exact:true}).fill(password);await page.getByRole('button',{name:'Masuk ke dashboard'}).click();await expect(page).toHaveURL(new RegExp('/'+role+'/dashboard$'));}
test('desktop admin, charts, filters, and report download',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await login(page,'admin','admin');await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible();await expect(page.locator('#weekly-chart')).toBeVisible();await page.screenshot({path:'.qa/dashboard-desktop.png',fullPage:true});
 await page.getByRole('link',{name:'Murid',exact:true}).click();await page.getByLabel('Cari murid').fill('Aditya');await page.getByRole('button',{name:'Filter',exact:true}).click();await expect(page.getByText('Aditya Pratama',{exact:true})).toBeVisible();
 await page.goto('/reports');const href=await page.getByRole('link',{name:'Review Laporan'}).first().getAttribute('href');await page.goto(href);const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download Excel'}).click();const file=await download;expect(file.suggestedFilename()).toMatch(/\.xlsx$/);await file.saveAs('.qa/browser-report.xlsx');expect(errors).toEqual([]);
});
test('mobile student navigation, forms, and card',async({page})=>{
 await page.setViewportSize({width:390,height:844});await page.goto('/');await page.screenshot({path:'.qa/login-mobile.png',fullPage:true});await login(page,'student','murid1@sekolah.test','0000001001');await page.screenshot({path:'.qa/dashboard-mobile.png',fullPage:true});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBeTruthy();await page.getByRole('button',{name:'Buka menu'}).click();await page.getByRole('link',{name:'Izin / Sakit',exact:true}).click();await page.getByLabel('Jenis ketidakhadiran').selectOption('SAKIT');await expect(page.getByLabel('Foto bukti',{exact:true})).toHaveAttribute('required','');await page.screenshot({path:'.qa/absence-mobile.png',fullPage:true});
 await page.goto('/cards');await page.getByRole('link',{name:'Preview',exact:true}).click();await expect(page.getByAltText('QR absensi Aditya Pratama')).toBeVisible();const download=page.waitForEvent('download');await page.getByRole('link',{name:'Download PDF'}).click();const file=await download;expect(file.suggestedFilename()).toMatch(/\.pdf$/);await file.saveAs('.qa/browser-card.pdf');await page.screenshot({path:'.qa/card-mobile.png',fullPage:true});
});
test('homeroom PIN opens only assigned classroom',async({page})=>{await login(page,'teacher','G001');await page.getByRole('link',{name:'Kelas Saya',exact:true}).click();await page.getByRole('link',{name:'Buka Kelas'}).first().click();await page.getByLabel('PIN kelas',{exact:true}).fill('246810');await page.getByRole('button',{name:'Buka Kelas'}).click();await expect(page.getByRole('heading',{name:'XI RPL 1',exact:true})).toBeVisible();await page.screenshot({path:'.qa/classroom-desktop.png',fullPage:true});});
test('QR image scanner decodes a real generated card and reaches server validation',async({page})=>{
 await login(page,'admin','admin');await page.goto('/scanner');const response=page.waitForResponse(r=>r.url().endsWith('/scanner')&&r.request().method()==='POST');await page.locator('#scan-file').setInputFiles(path.resolve('.qa/demo-qr.png'));const res=await response;expect([200,422]).toContain(res.status());const data=await res.json();expect(data.errors?.qr).toBeUndefined();await expect(page.locator('#scan-result')).not.toContainText('tidak terbaca');await page.screenshot({path:'.qa/scanner-image.png',fullPage:true});
});
test('camera scanner decodes synthetic video without video capture',async({page})=>{
 await login(page,'admin','admin');await page.goto('/scanner');const result=await page.evaluate(async()=>{try{const {Html5Qrcode}=await import('/vendor-tmp/html5-qrcode.esm.js');const buf=await (await fetch('/vendor-tmp/frame1.png')).arrayBuffer();const qr=new Html5Qrcode('qr-reader',{verbose:false});const text=await qr.scanFileV2(new File([buf],'f.png',{type:'image/png'}),false);const input=document.querySelector('input[name=scan_type]:checked');const res=await fetch(document.getElementById('scanner-page').dataset.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({qr:text.decodedText,type:input.value})});return {decoded:text.decodedText,status:res.status,body:await res.json()};}catch(e){return {error:String(e)};}});console.log('SCAN RESULT: '+JSON.stringify(result));expect(result.error).toBeUndefined();expect([200,422]).toContain(result.status);expect(result.body?.errors?.qr).toBeUndefined();expect(result.decoded).toBeTruthy();
});
