@extends('layouts.app')
@section('title','Dashboard')
@section('content')
<div class="page-heading"><div><div class="eyebrow">GAMBARAN UMUM SEKOLAH</div><h1>Dashboard</h1><p>Pantau kehadiran, dukung setiap langkah belajar.</p></div><div class="actions"><a class="btn secondary" href="{{ route('reports.index') }}"><x-icon name="download"/>Laporan</a><a class="btn" href="{{ route('scanner') }}"><x-icon name="scan-line"/>Buka Scanner</a></div></div>
<div class="welcome-banner"><div><div class="eyebrow">SEMANGAT UNTUK HARI INI</div><h2>Selamat datang, {{ explode(' ',auth()->user()->name)[0] }} <span class="text-lg">☀</span></h2><p>Semua aktivitas kehadiran sekolah dalam satu tempat. Ada {{ $pending }} permohonan yang menunggu pemeriksaan.</p></div><a class="btn secondary !bg-white/60" href="{{ route('admin.requests',['status'=>'PENDING']) }}">Lihat permohonan<x-icon name="arrow-up-right"/></a><div class="banner-icon"><x-icon name="sprout"/></div></div>
<div class="stat-grid">@foreach([['Total murid',$totals['students'],'users','Murid aktif terdaftar'],['Total guru',$totals['teachers'],'contact-round','Guru aktif terdaftar'],['Total kelas',$totals['classes'],'school','Ruang belajar aktif'],['Hadir hari ini',$stats['HADIR']+$stats['TERLAMBAT'],'user-check','Termasuk hadir terlambat']] as $i=>[$label,$value,$icon,$caption])<div class="stat-card {{ $i===3?'featured':'' }}"><div class="stat-top">{{ $label }}<span class="stat-icon"><x-icon :name="$icon"/></span></div><strong>{{ number_format($value,0,',','.') }}</strong><small>{{ $caption }}</small></div>@endforeach</div>
<x-status-stats :stats="$stats"/><x-charts :weekly="$weekly" :monthly="$monthly" :month-stats="$monthStats" :percent="$percent"/>
<div class="lower-grid"><section class="panel"><div class="panel-head"><div><h2>Aktivitas terbaru</h2><p>Catatan kehadiran hari ini.</p></div><a href="{{ route('admin.attendance',['date'=>today()->toDateString()]) }}" class="text-link">Lihat semua ↗</a></div><x-attendance-table :rows="$recent"/><div class="panel-footer">Diperbarui dari database · {{ now()->format('H:i') }} WIB</div></section><section class="panel"><div class="panel-head"><div><h2>Agenda sekolah</h2><p>Ada hal baik yang menanti.</p></div><x-icon name="calendar-days" class="text-stone-400"/></div><div class="panel-body">@forelse($events as $event)<div class="agenda-item"><div class="agenda-date"><strong>{{ $event->starts_on->format('d') }}</strong><small>{{ $event->starts_on->translatedFormat('M') }}</small></div><div><h3>{{ $event->title }}</h3><p>{{ $event->type }} · {{ $event->attendance_active?'Absensi aktif':'Libur absensi' }}</p></div></div>@empty<x-empty title="Belum ada agenda" text="Tambahkan kegiatan pada kalender akademik."/>@endforelse</div><div class="panel-footer"><a class="text-link" href="{{ route('calendar.index') }}">Buka kalender akademik →</a></div></section></div>
<section class="panel"><div class="panel-head"><div><h2>Kehadiran bulan ini</h2><p>Jumlah hadir dan terlambat per hari, {{ now()->translatedFormat('F Y') }}.</p></div><span class="badge">BULANAN</span></div><div class="panel-body"><div class="chart-wrap !h-40"><canvas id="monthly-chart" aria-label="Grafik kehadiran bulanan" role="img"></canvas></div></div></section>
@endsection
