@extends('layouts.app')
@section('title',($person?'Edit ':'Tambah ').($kind==='students'?'Murid':'Guru'))
@section('content')
@php($student=$kind==='students')
@php($user=$person?->user)
<div class="page-heading"><div><div class="eyebrow">DIREKTORI SEKOLAH</div><h1>{{ $person?'Edit':'Tambah' }} {{ $student?'Murid':'Guru' }}</h1><p>Identitas lengkap untuk layanan sekolah yang lebih baik.</p></div><a class="btn secondary" href="{{ route('admin.'.$kind.'.index') }}"><x-icon name="arrow-left"/>Kembali</a></div>
<form class="panel" method="post" enctype="multipart/form-data" action="{{ $person?route('admin.'.$kind.'.update',$person):route('admin.'.$kind.'.store') }}">@csrf @if($person)@method('PUT')@endif
<div class="form-section"><h2>Identitas & akun</h2><p>Akun dan kartu QR dibuat otomatis saat data baru disimpan.</p><div class="form-grid"><x-field name="name" label="Nama lengkap" :value="$user?->name" required maxlength="100"/><x-field :name="$student?'nisn':'employee_id'" :label="$student?'NISN (10 digit)':'ID / NIP Guru'" :value="$person?->nisn??$person?->employee_id" required/>
<x-field name="email" label="Email" type="email" :value="$user?->email" required/><x-field name="password" :label="$person?'Password baru (opsional)':'Password awal'" type="password" minlength="8" maxlength="128" :required="!$person" autocomplete="new-password" hint="Minimal 8 karakter. Sampaikan secara pribadi kepada pemilik akun."/>
<x-field name="phone" label="Nomor telepon" type="tel" :value="$user?->phone" maxlength="30"/><x-select name="active" label="Status akun" :options="[1=>'Aktif',0=>'Nonaktif']" :value="$user?(int)$user->active:1" required/>
@if($student)<x-select name="gender" label="Jenis kelamin" :options="['L'=>'Laki-laki','P'=>'Perempuan']" :value="$person?->gender" required placeholder="Pilih jenis kelamin"/><x-field name="birth_date" label="Tanggal lahir" type="date" :value="$person?->birth_date?->toDateString()"/><x-select name="school_class_id" label="Kelas" :options="$classes->mapWithKeys(fn($c)=>[$c->id=>$c->name.' · '.$c->academic_year])" :value="$person?->school_class_id" required placeholder="Pilih kelas"/>@else<x-field name="position" label="Jabatan" :value="$person?->position" required maxlength="100"/>@endif
<x-field name="photo" label="Foto profil" type="file" accept="image/jpeg,image/png,image/webp" hint="JPG, PNG, atau WebP. Maksimal 2 MB, 4000 × 4000 px."/><div class="field full"><label for="address">Alamat</label><textarea id="address" name="address" rows="3" maxlength="1000">{{ old('address',$person?->address) }}</textarea></div></div></div>
@if($student)<div class="form-section"><h2>Orang tua / wali</h2><p>Kontak wali untuk pendampingan dan pusat notifikasi internal.</p><div class="form-grid"><x-field name="guardian_name" label="Nama wali" :value="$person?->parentGuardian?->name" required/><x-field name="guardian_relationship" label="Hubungan" :value="$person?->parentGuardian?->relationship" placeholder="Ayah / Ibu / Wali" required/><x-field name="guardian_phone" label="Nomor telepon wali" type="tel" :value="$person?->parentGuardian?->phone" required/><x-field name="guardian_email" label="Email wali (opsional)" type="email" :value="$person?->parentGuardian?->email"/></div></div>@endif
<div class="form-actions"><a class="btn secondary" href="{{ route('admin.'.$kind.'.index') }}">Batal</a><button class="btn"><x-icon name="check"/>Simpan {{ $student?'Murid':'Guru' }}</button></div></form>
@endsection
