<!DOCTYPE html>
<html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="csrf-token" content="{{ csrf_token() }}"><title>@yield('title','Dashboard') · {{ $schoolSettings->school_name }}</title><link rel="manifest" href="{{ asset('manifest.json') }}"><meta name="theme-color" content="#087b68"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="apple-touch-icon" href="{{ asset('icons/icon-192.png') }}"><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml">@vite(['resources/css/app.css','resources/js/app.js'])<script>if('serviceWorker' in navigator){addEventListener('load',()=>navigator.serviceWorker.register('{{ asset('sw.js') }}'));}</script></head>
<body><a href="#main-content" class="sr-only focus:not-sr-only">Lewati navigasi</a><div class="app-shell"><button class="overlay" data-menu-close aria-label="Tutup menu"></button>
<aside class="sidebar" aria-label="Menu utama"><a class="brand" href="{{ route(auth()->user()->homeRoute()) }}"><span class="brand-mark"><x-icon name="graduation-cap"/></span><span><strong>{{ $schoolSettings->school_name }}</strong><small>Absensi digital</small></span></a>
@php
$role=auth()->user()->role;
$links=$role==='admin' ? [
 ['admin.dashboard','layout-dashboard','Dashboard'],['admin.students.index','users','Murid'],['admin.teachers.index','contact-round','Guru'],['admin.classes.index','school','Kelas'],['admin.attendance','clipboard-check','Absensi'],['scanner','scan-line','QR Scanner'],['admin.requests','file-clock','Permohonan Izin'],['calendar.index','calendar-days','Kalender Akademik'],['reports.index','chart-no-axes-combined','Laporan'],['cards.index','id-card','Kartu']
]:[
 [$role.'.dashboard','layout-dashboard','Dashboard'],[$role.'.attendance','fingerprint','Absen'],[$role.'.history','history','Riwayat Absensi'],['cards.index','id-card',$role==='student'?'Kartu Pelajar':'Kartu Guru'],['calendar.index','calendar-days','Kalender']
];
if($role==='student')$links[]= ['student.absences.index','file-clock','Izin / Sakit'];
if($role==='teacher' && auth()->user()->teacher?->homeroomClasses()->where('active',true)->exists()){$links[]=['teacher.classes.index','school','Kelas Saya'];$links[]=['reports.index','chart-no-axes-combined','Laporan Kelas'];}
@endphp
<nav class="nav"><div class="nav-label">MENU UTAMA</div>@foreach($links as [$route,$icon,$label])<a href="{{ route($route) }}" class="{{ request()->routeIs(str_replace('.index','.*',$route))?'active':'' }}"><x-icon :name="$icon"/>{{ $label }}</a>@endforeach
<div class="nav-label">PREFERENSI</div>@if($role==='admin')<a href="{{ route('admin.settings.edit') }}" class="{{ request()->routeIs('admin.settings.*')?'active':'' }}"><x-icon name="sliders-horizontal"/>Pengaturan Absensi</a>@endif
<a href="{{ route('notifications.index') }}" class="{{ request()->routeIs('notifications.*')?'active':'' }}"><x-icon name="bell"/>Notifikasi</a><a href="{{ route('profile.edit') }}" class="{{ request()->routeIs('profile.*')?'active':'' }}"><x-icon name="circle-user-round"/>Profil Saya</a></nav>
<div class="sidebar-note"><div class="eyebrow">Satu langkah lebih tertib</div><p class="text-xs text-stone-500">Kehadiran kecil hari ini,<br>masa depan besar nanti.</p></div>
<div class="sidebar-footer"><x-avatar :user="auth()->user()"/><div class="min-w-0 flex-1"><strong class="truncate">{{ auth()->user()->name }}</strong><small>{{ ['admin'=>'Administrator','teacher'=>'Guru','student'=>'Murid'][$role] }}</small></div><form method="post" action="{{ route('logout') }}">@csrf<button class="icon-button" aria-label="Logout" title="Logout"><x-icon name="log-out"/></button></form></div></aside>
<div class="main-wrap"><header class="topbar"><div class="flex items-center gap-3"><button type="button" class="icon-button mobile-menu" data-menu-toggle aria-label="Buka menu" aria-expanded="false"><x-icon name="menu"/></button><div class="breadcrumb"><span>Workspace</span><x-icon name="chevron-right" class="!w-3 !h-3"/><strong>@yield('title','Dashboard')</strong></div></div><div class="top-actions"><span class="top-date">{{ today()->translatedFormat('l, d F Y') }}</span><a href="{{ route('notifications.index') }}" class="icon-button notification-button" aria-label="Notifikasi"><x-icon name="bell"/>@if(auth()->user()->unreadNotifications()->exists())<span class="dot"></span>@endif</a><a href="{{ route('profile.edit') }}" aria-label="Profil"><x-avatar :user="auth()->user()"/></a></div></header>
<main id="main-content" class="content"><x-alerts/>@yield('content')<footer class="footer"><span>© {{ date('Y') }} {{ $schoolSettings->school_name }} · Sistem Absensi Digital Sekolah</span><span><i class="live-dot"></i>Waktu Indonesia Barat</span></footer></main></div></div>
<dialog id="confirm-dialog"><h2>Konfirmasi tindakan</h2><p id="confirm-message"></p><div class="actions"><button type="button" class="btn secondary" id="confirm-cancel">Batal</button><button type="button" class="btn danger" id="confirm-yes">Ya, lanjutkan</button></div></dialog>
@stack('scripts')</body></html>
